In [1]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv('/content/Zomato-data-.csv')

In [4]:
###df['Name'] = df['Name'].str.replace('/', '', regex=False)
df['rate']=df['rate'].str.replace('/','',regex=False)

In [5]:
df.head(2)

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
0,Jalsa,Yes,Yes,4.15,775,800,Buffet
1,Spice Elephant,Yes,No,4.15,787,800,Buffet

In [6]:
####df['Gender'].value_counts()
###df['online_order']=df['online_order'].value_counts()
df.groupby(['online_order']).count()
###df['online_order']=='No'

,name,book_table,rate,votes,approx_cost(for two people),listed_in(type)
online_order,,,,,,
No,90,90,90,90,90,90
Yes,58,58,58,58,58,58

In [7]:
df.tail(2)

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
146,Darbar,No,No,3.05,98,800,Dining
147,Vijayalakshmi,Yes,No,3.95,47,200,Dining

In [9]:
df[df['book_table']=='Yes'].head(2)

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
0,Jalsa,Yes,Yes,4.15,775,800,Buffet
7,Onesta,Yes,Yes,4.65,2556,600,Cafes

In [10]:
###How many restaurants provide online ordering and how many do not?
online_order_counts = df['online_order'].value_counts()
print(online_order_counts)

online_order
No     90
Yes    58
Name: count, dtype: int64

In [11]:
###How many restaurants provide both online ordering and table booking?
online_and_Table_Booking=df[(df["online_order"]=='Yes') & (df["book_table"]=='Yes')]
print(online_and_Table_Booking)

                name online_order book_table  rate  votes  \
0              Jalsa          Yes        Yes  4.15    775
7             Onesta          Yes        Yes  4.65   2556
11      Cafe Shuffle          Yes        Yes  4.25    150
12  The Coffee Shack          Yes        Yes  4.25    164
44            Onesta          Yes        Yes  4.65   2556
57            Wamama          Yes        Yes  4.25    354
61          Goa 0 Km          Yes        Yes  3.65    163

    approx_cost(for two people) listed_in(type)
0                           800          Buffet
7                           600           Cafes
11                          600           Cafes
12                          500           Cafes
44                          600           other
57                          800           other
61                          800          Dining

In [12]:
###List the top 10 restaurants based on ratings.
Top_10_restaurants=df.sort_values(by='rate',ascending=False).head(10)

In [13]:
Top_10_restaurants

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
44,Onesta,Yes,Yes,4.65,2556,600,other
7,Onesta,Yes,Yes,4.65,2556,600,Cafes
38,Empire Restaurant,Yes,No,4.45,4884,750,other
86,Meghana Foods,Yes,No,4.45,4401,600,Dining
52,Corner House Ice Cream,No,No,4.35,345,400,Dining
37,Szechuan Dragon,Yes,No,4.25,1647,600,Dining
60,Peppy Peppers,No,No,4.25,244,800,other
81,Frozen Bottle,Yes,No,4.25,146,400,Dining
12,The Coffee Shack,Yes,Yes,4.25,164,500,Cafes
11,Cafe Shuffle,Yes,Yes,4.25,150,600,Cafes

In [14]:
###List the bottom 10 restaurants based on ratings.
bottom_10_restaurants=df.sort_values(by='rate',ascending=False).tail(10)

In [15]:
bottom_10_restaurants

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
124,Kwality Wall's Swirl's Happiness Station,No,No,2.95,25,200,Dining
73,LSD Cafe,No,No,2.95,84,700,other
137,Hotel Andhra Speices,No,No,2.95,0,250,Dining
138,Sri Murari Family Restaurant,No,No,2.95,0,250,Dining
139,Aramane Donne Biriyani,No,No,2.95,0,150,Dining
126,Banashankari Nati Style,No,No,2.95,0,350,Dining
125,Soms Kitchen & Bakes,No,No,2.95,0,400,Dining
31,Foodiction,Yes,No,2.85,506,500,other
36,Fast And Fresh,Yes,No,2.85,91,400,Dining
94,Nandhini Deluxe,No,No,2.65,283,600,Dining

In [ ]:
###Identify the top 50 budget-friendly restaurants that are also customer-friendly.

In [ ]:
###Identify the top 20 budget-friendly restaurants by listed type that are also customer-friendly.

In [16]:
###How many restaurants are there in total?
Count_Of_restaurants = df['name'].nunique()
Count_Of_restaurants

145

In [18]:
###How many restaurants fall under each listed_in(type) category?
category_counts = df.groupby('listed_in(type)')['name'].nunique()
category_counts

listed_in(type)
Buffet      7
Cafes      23
Dining    110
other       8
Name: name, dtype: int64

In [19]:
###What is the average rating of restaurants that provide online ordering vs. those that do not?
avg_ratings = df.groupby('online_order')['rate'].mean()
avg_ratings

TypeError: agg function failed [how->mean,dtype->object]

In [ ]:
###What is the average cost (for two) of restaurants that allow table booking vs. those that do not?

In [20]:
###Find the restaurant(s) with the highest number of votes.
max_Vote=df[df['votes']==max(df['votes'])]
max_Vote

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
38,Empire Restaurant,Yes,No,4.45,4884,750,other

In [21]:
###Find the restaurant(s) with the lowest rating but more than 200 votes.
min_rating=df[(df['rate']==min(df['rate'])) & (df['votes']>200)]
min_rating

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
94,Nandhini Deluxe,No,No,2.65,283,600,Dining

In [23]:
###List all restaurants where the cost is above the overall average cost.
avg_cost=df[df['approx_cost(for two people)']>df['approx_cost(for two people)'].mean()]
avg_cost.head(2)

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
0,Jalsa,Yes,Yes,4.15,775,800,Buffet
1,Spice Elephant,Yes,No,4.15,787,800,Buffet

In [ ]:
### Find the most common cost value (mode) among all restaurants.

In [ ]:
## Create a new column rating_value (extract numeric value from rate). Then, find the highest-rated restaurant under each listed_in(type).

In [26]:
## Find how many restaurants have a cost ≤500 and a rating ≥4.0.
df[(df['approx_cost(for two people)']<=500) & (df['rate']>='4.0')].head(2)

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
10,Village Café,Yes,No,4.15,402,500,Cafes
12,The Coffee Shack,Yes,Yes,4.25,164,500,Cafes

In [28]:
## Find the restaurant(s) where cost is highest but rating is still below 3.5.
df[(df['approx_cost(for two people)']>=df['approx_cost(for two people)'].mean()) & (df['rate']<'3.5')].head(2)

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
25,CAFE NOVA,No,No,3.25,11,600,Cafes
27,Sea Green Cafe,No,No,3.35,4,500,Cafes

In [38]:
## Group restaurants by online_order and calculate: average votes, average cost, and average rating.
Result=df.groupby('online_order').agg(avg_vote=('votes','mean'),avg_cost=('approx_cost(for two people)','mean')
###,avg_rating=('rate','mean')
)
print(Result)

                avg_vote    avg_cost
online_order
No             75.222222  358.888889
Yes           559.000000  510.344828

In [33]:
## Group restaurants by book_table and calculate the total number of votes.
Result=df.groupby('book_table')['votes'].sum()
Result

book_table
No     31666
Yes     7526
Name: votes, dtype: int64

In [ ]:
## Find the ratio of restaurants that allow both online_order and book_table to total restaurants.

In [ ]:
## Find restaurants where votes are in the top 10% but rating_value is below 4.0.

In [ ]:
### dd a column budget_category with: “Low” (≤500), “Medium” (501–800), “High” (>800). Count restaurants in each category.

In [39]:
df.head(1)

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
0,Jalsa,Yes,Yes,4.15,775,800,Buffet

In [42]:
## Find the cheapest restaurant in each listed_in(type) category.
df.groupby('listed_in(type)')['approx_cost(for two people)'].min()

listed_in(type)
Buffet    300
Cafes     200
Dining    100
other     500
Name: approx_cost(for two people), dtype: int64

In [ ]:
## Find restaurants that have duplicate approx_cost(for two people) but different ratings.

In [ ]:
## Which restaurants have identical votes but different ratings?

In [ ]:
## Calculate the correlation between votes and rating_value